### ISSUE TITLE
Magic Numbers in get_model_recon() in metrics.py.

### ISSUE THREAD

**Issue by zparis99** [leoniekerken/ECoG-foundation-model#1]
In metrics.py there is an assumption in get_model_recon that there is a batch size of at least 9 and 5 bands (see definition of x and y below.
```
def get_model_recon(signal, recon_signal, epoch):

    res_list = []
    i = 1

    for h in range(0, 8):
        for w in range(0, 8):

            res = {}
            res["epoch"] = epoch
            res["elec"] = i
            i += 1

            x = signal[8, 4, :, 0, h, w].flatten()
            y = recon_signal[8, 4, :, 0, h, w].flatten()

            if np.isnan(x).any() or np.isnan(y).any():
                continue

            res["x"] = [x]
            res["y"] = [y]

            res_list.append(res.copy())

    new_model_recon = pd.DataFrame(res_list)

    return new_model_recon
```

I was trying to overfit a model to a single batch to make sure that the model was actually learning from the data but was having an issue as a result of this code looking in the 8th index of the batch dimension. I was able to get a model to train though when I set the batch size to 9.  I still don't totally understand the training code (working on it) but I'm confused what's so special about the 8th batch and 4th band here. It looks like this is used to write a dataframe so we can look at some of the reconstructed signals compared to the original signal. 

To keep the fix simple could we just change these to look at the 0th batch index and the 0th band? That way as long as your batch size is >= 1 and you have >= 1 bands this won't error out?

**Comment by leoniekerken** [comment]
Good point! We are mostly interested in the 5th band (high gamma) because this is most relevant to our research purposes, and for now we also continue to train on all bands. But we should make this part of the code more flexible for cases when we do not train on all bands! Regarding the batch, we can just set it to the 0th batch!

**Comment by zparis99** [comment]
Awesome thanks! I'll close this issue.
