### ISSUE TITLE
Add mae_st model support

### ISSUE THREAD

**Issue by itamarJa** [leoniekerken/ECoG-foundation-model#24]
Try implementing the MAE_st architecture on the data and test encoding and decoding performance. 
This can be based on the fMRI foundation repo (https://github.com/MedARC-AI/fMRI-foundation-model). The original repo is: https://github.com/facebookresearch/mae_st

**Comment by zparis99** [comment]
Because I've been having trouble with the current training loop and the fmri project found that this implementation performed better, I'm going to switch over to adding this support so we can use this instead.

**Comment by zparis99** [comment]
Support is setup in the mae-st branch. I'm currently using this for most of my experiments.
